#!/bin/bash -l
#SBATCH --account=OD-220461
#SBATCH --job-name=differencing_TB
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200gb
#SBATCH --time=3:00:00

##SBATCH --mail-type=ALL
##SBATCH --mail-user=b.maslen@unsw.edu.au

cd /datasets/work/d61-icv-rpsa/work/Ben_M/Movement_OD_WD/code/augmentation/

module load python/3.9.4

source augm_venv/bin/activate

python -m differencing -l '../../data/Tassy_BRUV/location_data/location_dat.csv'\
 -t '../../data/Tassy_BRUV/training_data/' -rs 1920 1080 -s 0 70 0 635 -c \
 -di '../../data/Tassy_BRUV/augmented_images/' -n 'naive_alpha_15_diff_2_t' \
-d 2 -m 'naive' -a 15
