#!/bin/bash -l
#SBATCH --account=OD-220461
#SBATCH --job-name=yolov5ms
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=256gb
#SBATCH --time=00:20:00

#SBATCH --gres=gpu:4
##SBATCH --mail-type=ALL
##SBATCH --mail-user=b.maslen@unsw.edu.au

cd /datasets/work/d61-icv-rpsa/work/Ben_M/Movement_OD_WD/code/yolov8

module load python/3.9.4

source yolov8_venv/bin/activate

yolov8_venv/bin/yolo detect train data=../../data/Tassy_BRUV/augmented_images/abs_alpha_7_diff_2_red/data.yaml \
model=models/yolov8n.pt epochs=5 imgsz=1280 device=0,1,2,3 workers=8 \
name=../../../../results/Tassy_BRUV/train/tassy_bruv_8m_abs_alpha_7_diff_2_red_5_test

yolov8_venv/bin/yolo detect val data=../../data/Tassy_BRUV/augmented_images/abs_alpha_7_diff_2_red/data.yaml \
model=../../results/Tassy_BRUV/train/tassy_bruv_8m_abs_alpha_7_diff_2_red_5_test/weights/best.pt imgsz=1280 device=0,1,2,3 \
split=test name=../../../../results/Tassy_BRUV/test/tassy_bruv_8m_abs_alpha_7_diff_2_red_5_test
